# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

strategy:
  matrix:
    jdk8_linux:
      imageName: "ubuntu-latest"
      jdkVersion: "1.8"
    jdk8_mac:
      imageName: "macOS-latest"
      jdkVersion: "1.8"
    jdk8_windows:
      imageName: "windows-latest"
      jdkVersion: "1.8"
    jdk11_linux:
      imageName: "ubuntu-latest"
      jdkVersion: "1.11"
    jdk11_mac:
      imageName: "macOS-latest"
      jdkVersion: "1.11"
    jdk11_windows:
      imageName: "windows-latest"
      jdkVersion: "1.11"
    default_linux:
      imageName: "ubuntu-latest"
      jdkVersion: "default"
    default_mac:
      imageName: "macOS-latest"
      jdkVersion: "default"
    default_windows:
      imageName: "windows-latest"
      jdkVersion: "default"
  maxParallel: 9

pool:
  vmImage: $(imageName)

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: $(jdkVersion)
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: PublishCodeCoverageResults@2
  inputs:
    summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml" # Path to summary files
    reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco" # Path to report directory
    failIfCoverageEmpty: true # Fail if code coverage results are missing
